org.gradle.caching=true
group=io.ballerina.lib
version=1.0.0
ballerinaLangVersion=2201.12.0

checkstylePluginVersion=10.12.0
spotbugsPluginVersion=6.0.18
githubShadowVersion=7.1.2
checkstyleToolVersion=10.12.0
shadowJarPluginVersion=8.1.1
downloadPluginVersion=5.4.0
releasePluginVersion=2.8.0
ballerinaGradlePluginVersion=2.3.0

# Standard library versions
stdlibIoVersion=1.8.0

# Dependencies
freemarkerVersion=2.3.33
jacksonVersion=2.18.6
