Args = --initialize-at-run-time=io.ballerina.lib.freemarker.FreemarkerUtils \
       --initialize-at-run-time=freemarker.template.Configuration \
       --initialize-at-run-time=freemarker.core.Configurable \
       --initialize-at-run-time=freemarker.log.Logger \
       --initialize-at-run-time=freemarker.ext.beans.BeansWrapper \
       --initialize-at-run-time=freemarker.ext.beans.BeansWrapperBuilder \
       --initialize-at-run-time=freemarker.template.DefaultObjectWrapper \
       --initialize-at-run-time=freemarker.template.DefaultObjectWrapperBuilder
